//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DebitManageSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class debit_table
    {
        public int debit_id { get; set; }
        public int depart_cd { get; set; }
        public int client_id { get; set; }
        public Nullable<int> debit_limited { get; set; }
        public string debit_rank { get; set; }
        public Nullable<System.DateTime> debit_deadline { get; set; }
    
        public virtual client_table client_table { get; set; }
        public virtual depart_table depart_table { get; set; }
    }
}
